### ISSUE TITLE
change name foundations to foundation

### ISSUE THREAD

**Issue by Mombuyish** [Mombuyish/Laravel-Oh-Generators#5]

**Comment by goodjack** [comment]
Why?

**Comment by Mombuyish** [comment]
We should follow laravel framework naming, make it looks like laravel.

https://github.com/laravel/framework/tree/5.8/src/Illuminate/Foundation

**Comment by goodjack** [comment]
This needs to be fixed:
https://github.com/Mombuyish/Laravel-Oh-Generators/wiki/Foundation

**Comment by Mombuyish** [comment]
@goodjack fixed, thanks.
